name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black
      - name: Run flake8
        run: |
          flake8 spark/spark_app/
      - name: Run black check
        run: |
          black --check spark/spark_app/
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov pytest-spark chispa
      - name: Download Spark
        run: |
          wget https://downloads.apache.org/spark/spark-3.5.3/spark-3.5.3-bin-hadoop3.tgz
          tar xvf spark-3.5.3-bin-hadoop3.tgz
          export SPARK_HOME=$PWD/spark-3.5.3-bin-hadoop3
          export PATH=$SPARK_HOME/bin:$PATH
          echo "SPARK_HOME=$SPARK_HOME" >> $GITHUB_ENV
          echo "PATH=$PATH" >> $GITHUB_ENV
      - name: Run pytest with coverage
        run: |
          pytest --cov=spark/spark_app --cov-report=xml spark/spark_app/tests/
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker images
        run: docker-compose build